### ISSUE TITLE
Email report via sendmail

### ISSUE THREAD

**Issue by GittyUpTom** [onesimus-systems/sysreporter#12]
I've modified my copy of sysreport to first look for ssmtp and then sendmail.
This is a simple modification that would expand the use of the sysreporter project.
Please give the attached patch consideration. 
[sysreport.patch.txt](https://github.com/onesimus-systems/sysreporter/files/299488/sysreport.patch.txt)

**Comment by lfkeitel** [comment]
Cool. That would be a wonderful addition. I've never set up sendmail and I've always use ssmtp so never thought of that. I'll definitely add it.

**Comment by lfkeitel** [comment]
Instead of doing nested ifs, I moved it to a setting that defaults to ssmtp but can easily be changed to sendmail. This way if there's yet another emailer someone wants to use, the main script doesn't need to be changed.

Closed with 452fd73. I forgot to tag the issue in the commit message.
